blog/blueprints/posts/views.py
# -*- coding: utf8 -*-
from datetime import datetime

from flask import (Blueprint, request, redirect, 
    render_template, url_for, session)
from flask.views import MethodView
from flask.ext.mongoengine.wtf import model_form

from models import Post, Comment
from utilities import login_required, uniq_list

posts = Blueprint('posts', __name__, template_folder='templates')

def check_slug_uniq(slug):
    try:
        post = Post.objects.get(slug=slug)
    except Post.DoesNotExist:
        return True
    else:
        return False


@posts.route('/')
def index():
    page = request.args.get('page', 1)

    paginated_posts = Post.objects.paginate(page=int(page), per_page=6)
    tags = Post.objects.item_frequencies('tags')

    return render_template('list_posts.html', pagination=paginated_posts, tags=tags)

@posts.route('/tags/<tag>')
def tags(tag):
    page = request.args.get('page', 1)

    paginated_posts = Post.objects(tags=tag).paginate(page=int(page), per_page=6)
    tags = Post.objects.item_frequencies('tags')

    return render_template('list_posts.html', pagination=paginated_posts, tags=tags, tag=tag)


@posts.route('/admin/posts/')
@login_required
def list_posts():
    posts = Post.objects.all()
    return render_template('list_posts_for_editing.html', posts=posts)


class DetailView(MethodView):
    form = model_form(Comment, exclude=['created_at'])

    def get_context(self, slug):
        post = Post.objects.get_or_404(slug=slug)
        form = self.form(request.form)

        context = {
            "post": post,
            "form": form
        }
        return context

    def get(self, slug):
        context = self.get_context(slug)
        return render_template('detail.html', **context)

    def post(self, slug):
        context = self.get_context(slug)
        form = context.get('form')

        if form.validate():
            comment = Comment()
            form.populate_obj(comment)

            post = context.get('post')
            post.comments.append(comment)
            post.save()

            return redirect(url_for('.detail', slug=slug))

        return render_template('detail.html', **context)


class NewPostView(MethodView):
    form = model_form(Post, 
        exclude=('created_at', 'comments', 'updated_at'))

    def get(self):
        return render_template('new.html', form=self.form())

    def post(self):
        form = self.form(request.form)
        tags = request.form['tags'] if request.form['tags'] else ''

        if form.validate():
            post = Post()
            form.populate_obj(post)

            tags = uniq_list(tags, ',')
            post['tags'] = tags

            post.save()

        return redirect(url_for('.index'))


class EditPost(MethodView):
    form = model_form(Post, 
        exclude=('created_at', 'comments', 'updated_at'))

    def get(self, slug):
        post = Post.objects.get_or_404(slug=slug)
        form = self.form()
        return render_template('edit.html', post=post, form=form)

    def post(self, slug):
        post = Post.objects.get_or_404(slug=slug)
        form = self.form(request.form)
        tags = request.form['tags'] if request.form['tags'] else ''

        if form.validate():
            now = datetime.now()

            for field in ['slug', 'title', 'body']:
                post[field] = form[field].data

            tags = uniq_list(tags, ',')
            post['tags'] = tags

            post['updated_at'] = now

            post.save()

        return redirect(url_for('.index'))

# Register the urls
posts.add_url_rule('/posts/<slug>/', view_func=DetailView.as_view('detail'))
posts.add_url_rule('/posts/new', view_func=login_required(NewPostView.as_view('new')))
posts.add_url_rule('/posts/<slug>/edit',view_func=login_required(EditPost.as_view('edit')))

blog/templates/autocomplete.html
{% macro autocomplete(elem_id, minlenght_in=1) -%}
<script>
    $(function() {
        $({{ elem_id }}).autocomplete({
            source: function(request, response) {
                $.getJSON(
                    "{{ url_for('apis.tagautocomplete') }}" + '?term=' + request.term,
                    function(data) {
                        if (data['items']) {
                            return response(data['items']);
                        }

                        return response([]);
                    }
                );
            },
            minLength: {{ minlenght_in }},
        });
    });
</script>
{%- endmacro %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pengfei Xue</title>
    <link href="/static/css/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="/static/css/bootstrap/bootstrap-responsive.css" rel="stylesheet">
    <link href="/static/css/blog.css" rel="stylesheet">
    <style>.content {padding-top: 80px;}</style>

    {% block css_header %}
    {% endblock %}
  </head>

  <body class="font-cute">

    <!-- Part 1: Wrap all page content here -->
    <div id='wrap'>
    {%- block topbar -%}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a href="/" class="brand">Pengfei Xue</a> 
            <span class="navbar-text">Starring to record my life here!</span>
            {% if 'uid' in session %}
                <a href="{{ url_for('posts.new') }}" class="btn btn-primary pull-right">New Post</a>
            {% endif %}
        </div>
      </div>
    </div>
    {%- endblock -%}

    <div class="container-fluid">
        <div class="row-fulid content">
            {% block sidebar %}
                <div class="span2 imgcenter-wrapper">
                    <img class="img-rounded" src="/static/images/pengfei.jpg">
                    <h2>
                        <span itemprop="name">@Beijing</span>
                    </h2>
                    <hr />
                    {% include 'tags.html' %}
                </div>
            {% endblock %}
            <div class="span7 offset1">
                {% block page_header %}{% endblock %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
    </div> <!-- Part 1: Wrap all page content here -->
    <div id="push"></div>

    <div id="footer">
        <div class="container">
            <div class="row-fluid">
                <div class="span2">
                    <img class="img-rounded" src="/static/images/sina_32x32.png">
                    <a href="http://weibo.com/u/1774807923"><span>Pengfei Xue</span></a>
                </div>

                <div class="span2">
                    <img class="img-rounded" src="/static/images/douban_32x32.png">
                    <a href="http://www.douban.com/people/xpen/"><span>豆瓣</span></a>
                </div>

                <div class="span2">
                    <img class="img-rounded" src="/static/images/alipay.png">
                    <a href="https://me.alipay.com/pengfeixue"><span>支付宝</span></a>
                </div>
            </div>
        </div>
    </div>

    {% include 'slide.html' %}

    <div class="hide">
        {% block js_footer %}
        {% endblock %}
        <script type="text/javascript" src="/static/js/jquery.js"></script>
        <script type="text/javascript" src="/static/js/bootstrap-carousel.js"></script>

        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-36753627-1']);
            _gaq.push(['_trackPageview']);

            (function() {
              var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
              ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
              var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </div>
  </body>
</html>

blog/templates/slide.html
<div id="cnbeta-rss" class="carousel slide fixed-at-bottom-right">
    <!-- Carousel items -->
    <div class="carousel-inner" id='cnbeta-tips'>
    <!-- Carousel nav -->
    </div>

    <div id="cnbeta-rss-bottom" class="carousel">
        <a class="pull-left" id="move-left" data-slide="prev">下页</a>
        <a class="pull-right" id="move-right" data-slide="next">上页</a>
    </div>

    <script type="text/javascript">
    $.getJSON(
        '{{ url_for('apis.cnbetacallpoint') }}', 
        function(data) {
            var tips = [];

            $.each(data.tips, function(index, tip) {
                tips.push(
                    '<div class="item">' + 
                        '<h3 class="popover-title">' + 
                            '<img src="/static/images/horn.svg">' + 
                            '<a href="' + tip.link + '" target="_blank">' + tip.title + 
                            '</a>' + 
                        '</h3>' + 
                        '<div class="popover-content alert alert-info">' + 
                        '<p>' + tip.content + '</p>' + 
                        '</div>' + 
                    '</div>'
                );
            });

            $('#cnbeta-tips').empty();
            $('#cnbeta-tips').append(tips.join(' '));
        }
    );
    $('.carousel').carousel({});

    $("#move-left").click(function() {
        $('.carousel').carousel('prev');
    });
    $("#move-right").click(function() {
        $('.carousel').carousel('next');
    });
    $("#cnbeta-tips").hover(function(){
        $("#cnbeta-rss-bottom").show();
    });
    </script>
</div>

blog/templates/tags.html
{% if tags %}
<div class="tags">
<h3> tags </h3>
<ul>
    {% for tag, count in tags.items() %}
        {% if tag %}
        <li><a class="tag{{ count % 5 }}" href="{{ url_for('posts.tags', tag=tag) }}">{{ tag }}</a></li>
        {% endif %}
    {% endfor %}
</ul>
</div>
{% endif %}